version: "3.4"

services:
  fooapp:
    build:
      context: ./fooapp
      args:
        API_URL: ${API_URL}
        HTTPS: ${HTTPS}
    networks:
      - dummynetwork

  barapp:
    build:
      context: ./barapp
      args:
        API_URL: ${API_URL}
        HTTPS: ${HTTPS}        
    networks:
      - dummynetwork

  api:
    build:
      context: ./api
    environment:
      - FOOAPP_URL=${FOOAPP_URL}
      - BARAPP_URL=${BARAPP_URL}
      - API_URL=${API_URL}
      - NODE_ENV=${NODE_ENV} 
      - HTTPS=${HTTPS} 
    networks:
      - dummynetwork

  gateway:
    build:
      context: ./gateway
    ports:
      - 80:80
      - 443:443
    environment:
      - FOOAPP_URL=${FOOAPP_URL}
      - BARAPP_URL=${BARAPP_URL}
      - API_URL=${API_URL}
      - NODE_ENV=${NODE_ENV} 
      - HTTPS=${HTTPS} 
    command: /bin/bash -c "envsubst '$${FOOAPP_URL},$${BARAPP_URL},$${API_URL},$${HTTPS}' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    networks:
      - dummynetwork
    depends_on:
      - fooapp
      - barapp
      - api

networks:
  dummynetwork:
